baseURL = 'https://www.jsongo.top/'
languageCode = 'zh-cn'
title = 'Ethan 的思考札记'
theme = 'stack'

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 5
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    tabWidth = 4
[markup.goldmark.parser.attribute]
    block = true